
services:
  # Serviço da Aplicação Node.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    ports:
      - "3000:3000" # Mapeia a porta 3000 do container para a porta 3000 do host
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/prison-management # URI do MongoDB
    depends_on:
      - mongo # Garante que o MongoDB esteja disponível antes de iniciar a aplicação
    volumes:
      - ./app:/app 
    restart: always

  # Serviço do MongoDB
  mongo:
    image: mongo:6.0
    container_name: mongo-db
    ports:
      - "27017:27017" # Mapeia a porta 27017 do container para a porta 27017 do host
    volumes:
      - mongo-data:/data/db # Persiste os dados do MongoDB em um volume
    restart: always

# Volumes para persistir os dados do MongoDB
volumes:
  mongo-data: